import { Match, Tournament, Team, Player, CricketServiceItem } from '@/lib/cricket/types';

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 'tourn-1',
    name: 'Bangalore Premier T20 Cup 2026',
    description: 'The premier local T20 tournament featuring 8 top city clubs competing for the grand championship trophy.',
    logo_url: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=1200&auto=format&fit=crop&q=80',
    format: 'T20',
    start_date: '2026-08-01',
    end_date: '2026-08-25',
    location: 'Bangalore Sports Complex Ground A',
    status: 'LIVE',
    entry_fee: 5000,
    prize_info: 'Winner: ₹100,000 | Runner-up: ₹50,000',
    rules: 'ICC T20 Rules. 20 Overs per innings. Maximum 4 overs per bowler.',
    created_at: '2026-07-20',
  },
  {
    id: 'tourn-2',
    name: 'Karnataka Super T10 Championship',
    description: 'Fast-paced T10 action packed tournament with aggressive batting and high energy matches.',
    logo_url: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1512716676800-4700e1fc70a1?w=1200&auto=format&fit=crop&q=80',
    format: 'T10',
    start_date: '2026-08-10',
    end_date: '2026-08-18',
    location: 'Chinnaswamy Practice Arena',
    status: 'REGISTRATION_OPEN',
    entry_fee: 3000,
    prize_info: 'Winner: ₹60,000 | Runner-up: ₹30,000',
    rules: '10 Overs per innings. Maximum 2 overs per bowler.',
    created_at: '2026-07-25',
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-1',
    tournament_id: 'tourn-1',
    name: 'Royal Panthers CC',
    logo_url: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'team-2',
    tournament_id: 'tourn-1',
    name: 'Deccan Strikers',
    logo_url: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'team-3',
    tournament_id: 'tourn-1',
    name: 'Koramangala Titans',
    logo_url: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'team-4',
    tournament_id: 'tourn-1',
    name: 'Indiranagar Warriors',
    logo_url: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=120&auto=format&fit=crop&q=80',
  },
];

export const MOCK_PLAYERS: Player[] = [
  {
    id: 'p-1',
    name: 'Rahul Sharma',
    team_id: 'team-1',
    team_name: 'Royal Panthers CC',
    jersey_number: 18,
    role: 'BATTER',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm medium',
    matches: 24,
    runs: 842,
    wickets: 2,
    average: 42.1,
    strike_rate: 144.5,
    economy: 8.2,
  },
  {
    id: 'p-2',
    name: 'Arun Kumar',
    team_id: 'team-1',
    team_name: 'Royal Panthers CC',
    jersey_number: 7,
    role: 'ALL_ROUNDER',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm offbreak',
    matches: 28,
    runs: 512,
    wickets: 34,
    average: 28.4,
    strike_rate: 132.0,
    economy: 7.1,
  },
  {
    id: 'p-3',
    name: 'Karthik Rao',
    team_id: 'team-2',
    team_name: 'Deccan Strikers',
    jersey_number: 99,
    role: 'BOWLER',
    batting_style: 'Right-hand bat',
    bowling_style: 'Right-arm fast',
    matches: 30,
    runs: 140,
    wickets: 45,
    average: 15.2,
    strike_rate: 98.4,
    economy: 6.8,
  },
  {
    id: 'p-4',
    name: 'Vikram Singh',
    team_id: 'team-2',
    team_name: 'Deccan Strikers',
    jersey_number: 10,
    role: 'WICKETKEEPER',
    batting_style: 'Left-hand bat',
    bowling_style: 'None',
    matches: 22,
    runs: 630,
    wickets: 0,
    average: 35.0,
    strike_rate: 138.2,
    economy: 0.0,
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: 'match-live-1',
    tournament_id: 'tourn-1',
    tournament_name: 'Bangalore Premier T20 Cup 2026',
    team_a: MOCK_TEAMS[0],
    team_b: MOCK_TEAMS[1],
    venue: {
      id: 'v-1',
      name: 'Central Sports Complex Ground A',
      address: 'Koramangala 4th Block',
      city: 'Bangalore',
      capacity: 2500,
    },
    scheduled_at: new Date().toISOString(),
    format: 'T20',
    overs: 20,
    status: 'LIVE',
    toss_winner_id: 'team-2',
    toss_decision: 'BAT',
    current_innings: {
      id: 'inn-2',
      match_id: 'match-live-1',
      batting_team_id: 'team-1',
      batting_team_name: 'Royal Panthers CC',
      innings_number: 2,
      runs: 142,
      wickets: 3,
      overs: 16.2,
      target: 175,
      status: 'IN_PROGRESS',
    },
    all_innings: [
      {
        id: 'inn-1',
        match_id: 'match-live-1',
        batting_team_id: 'team-2',
        batting_team_name: 'Deccan Strikers',
        innings_number: 1,
        runs: 174,
        wickets: 6,
        overs: 20.0,
        status: 'COMPLETED',
      },
      {
        id: 'inn-2',
        match_id: 'match-live-1',
        batting_team_id: 'team-1',
        batting_team_name: 'Royal Panthers CC',
        innings_number: 2,
        runs: 142,
        wickets: 3,
        overs: 16.2,
        target: 175,
        status: 'IN_PROGRESS',
      },
    ],
  },
  {
    id: 'match-up-1',
    tournament_id: 'tourn-1',
    tournament_name: 'Bangalore Premier T20 Cup 2026',
    team_a: MOCK_TEAMS[2],
    team_b: MOCK_TEAMS[3],
    venue: {
      id: 'v-2',
      name: 'HSR Layout Cricket Ground',
      address: 'HSR Sector 2',
      city: 'Bangalore',
      capacity: 1500,
    },
    scheduled_at: '2026-08-17T10:00:00.000Z',
    format: 'T20',
    overs: 20,
    status: 'UPCOMING',
  },
  {
    id: 'match-comp-1',
    tournament_id: 'tourn-1',
    tournament_name: 'Bangalore Premier T20 Cup 2026',
    team_a: MOCK_TEAMS[0],
    team_b: MOCK_TEAMS[2],
    venue: {
      id: 'v-1',
      name: 'Central Sports Complex Ground A',
      address: 'Koramangala 4th Block',
      city: 'Bangalore',
      capacity: 2500,
    },
    scheduled_at: '2026-08-14T10:00:00.000Z',
    format: 'T20',
    overs: 20,
    status: 'COMPLETED',
    winner_id: 'team-1',
    result_summary: 'Royal Panthers CC won by 18 runs',
    all_innings: [
      {
        id: 'inn-comp-1',
        match_id: 'match-comp-1',
        batting_team_id: 'team-1',
        batting_team_name: 'Royal Panthers CC',
        innings_number: 1,
        runs: 188,
        wickets: 4,
        overs: 20.0,
        status: 'COMPLETED',
      },
      {
        id: 'inn-comp-2',
        match_id: 'match-comp-1',
        batting_team_id: 'team-2',
        batting_team_name: 'Koramangala Titans',
        innings_number: 2,
        runs: 170,
        wickets: 9,
        overs: 20.0,
        target: 189,
        status: 'COMPLETED',
      },
    ],
  },
];

export const MOCK_SERVICES: CricketServiceItem[] = [
  {
    id: 'srv-1',
    name: 'Turf Ground Booking - Turf A',
    description: 'Standard floodlit synthetic turf ground for day/night T20 and T10 matches. Includes pavilion & commentary box.',
    image_url: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=600&auto=format&fit=crop&q=80',
    price: 1500,
    location: 'Koramangala, Bangalore',
    availability: 'Available Today',
    provider_name: 'Bangalore Turf Arena',
    provider_contact: '+91 98765 43210',
  },
  {
    id: 'srv-2',
    name: 'Certified Digital Live Scorer Service',
    description: 'Professional certified scorer equipped with tablet for live ball-by-ball scoring, wagon wheel & real-time updates.',
    image_url: 'https://images.unsplash.com/photo-1512716676800-4700e1fc70a1?w=600&auto=format&fit=crop&q=80',
    price: 800,
    location: 'Citywide Bangalore',
    availability: 'Instant Booking',
    provider_name: 'CrickScore Scorer Network',
    provider_contact: '+91 98765 00000',
  },
  {
    id: 'srv-3',
    name: 'Official Umpiring Panel (2 Umpires)',
    description: 'Pair of experienced state-level umpires with neutral officiating for tournament & club matches.',
    image_url: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&auto=format&fit=crop&q=80',
    price: 2000,
    location: 'Bangalore & Surrounds',
    availability: 'Available Weekends',
    provider_name: 'Karnataka Umpire Guild',
    provider_contact: '+91 98111 22233',
  },
  {
    id: 'srv-4',
    name: 'Full Match Live Stream & Drone Coverage',
    description: 'HD multi-camera live stream setup to YouTube/Facebook with dynamic score overlays.',
    image_url: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=600&auto=format&fit=crop&q=80',
    price: 4500,
    location: 'Karnataka',
    availability: 'Advance Booking',
    provider_name: 'StreamCricket Pro',
    provider_contact: '+91 99887 76655',
  },
];
